[profile.default]
    evm_version ="paris"
    libs        =["lib"]
    out         ="out"
    remappings  =["forge-std/=lib/forge-std/src/", "solady/=lib/solady/src"]
    solc_version="0.8.23"
    src         ="src"


[profile.deploy]
    fs_permissions=[{access="read", path="./out"}]
    optimizer     =true
    optimizer_runs=10_000_000
    via_ir        =true
